# Generated by Django 5.2.5 on 2025-08-15 03:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendarios',
            fields=[
                ('id_calendario', models.AutoField(primary_key=True, serialize=False)),
                ('novedad', models.TextField()),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
            ],
            options={
                'db_table': 'calendarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contenedores',
            fields=[
                ('id_contenedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_contenedor', models.CharField(max_length=50)),
                ('color_contenedor', models.CharField(max_length=20)),
                ('capacidad_total', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('fecha_instalacion', models.DateField(blank=True, null=True)),
                ('ultimo_vaciado', models.DateTimeField(blank=True, null=True)),
                ('descripcion_ubicacion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'contenedores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Coordenadas',
            fields=[
                ('id_coordenada', models.AutoField(primary_key=True, serialize=False)),
                ('archivo_coordenada', models.JSONField(blank=True, null=True, unique=True)),
                ('tipo_archivo', models.CharField(blank=True, max_length=30, null=True)),
                ('coordenada', models.TextField(blank=True, null=True, unique=True)),
                ('tipo_coordenada', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'coordenadas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Direcciones',
            fields=[
                ('id_direccion', models.AutoField(primary_key=True, serialize=False)),
                ('calle', models.CharField(blank=True, max_length=100, null=True)),
                ('numero', models.CharField(blank=True, max_length=10, null=True)),
                ('barrio', models.CharField(blank=True, max_length=50, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=50, null=True)),
                ('codigo_postal', models.CharField(blank=True, max_length=20, null=True)),
                ('provincia', models.CharField(blank=True, max_length=100, null=True)),
                ('pais', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'direcciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estados',
            fields=[
                ('id_estado', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_estado', models.DateTimeField(blank=True, null=True)),
                ('volumen', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
            ],
            options={
                'db_table': 'estados',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mapas',
            fields=[
                ('id_mapa', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_mapa', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'mapas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MedicionSensores',
            fields=[
                ('id_medicion_sensor', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora_medicion', models.DateTimeField()),
                ('porcentaje_ocupacion', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('volumen_medido', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('alerta_generada', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'medicion_sensores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Notificaciones',
            fields=[
                ('id_notificacion', models.AutoField(primary_key=True, serialize=False)),
                ('mensaje', models.TextField()),
                ('fecha_envio', models.DateTimeField()),
                ('tipo_notificacion', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'notificaciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegistroRecolecciones',
            fields=[
                ('id_registro_recoleccion', models.AutoField(primary_key=True, serialize=False)),
                ('volumen', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fecha_hora_recoleccion', models.DateTimeField()),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'registro_recolecciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Residuos',
            fields=[
                ('id_residuo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('imagen', models.CharField(blank=True, max_length=255, null=True)),
                ('categoria', models.CharField(blank=True, max_length=50, null=True)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('instruccion_reciclado', models.TextField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'residuos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sensores',
            fields=[
                ('id_sensor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_sensor', models.CharField(max_length=50)),
                ('fecha_instalacion_sensor', models.DateField(blank=True, null=True)),
                ('numero_serie', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'sensores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SpatialRefSys',
            fields=[
                ('srid', models.IntegerField(primary_key=True, serialize=False)),
                ('auth_name', models.CharField(blank=True, max_length=256, null=True)),
                ('auth_srid', models.IntegerField(blank=True, null=True)),
                ('srtext', models.CharField(blank=True, max_length=2048, null=True)),
                ('proj4text', models.CharField(blank=True, max_length=2048, null=True)),
            ],
            options={
                'db_table': 'spatial_ref_sys',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoEstados',
            fields=[
                ('id_tipo_estado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_estados', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'tipo_estados',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoUsuarios',
            fields=[
                ('id_tipo_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_usuario', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'tipo_usuarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsuariosHistorialesResiduos',
            fields=[
                ('id_usuario_historial_residuos', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_total', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('unidad', models.CharField(blank=True, max_length=10, null=True)),
                ('ultima_actualizacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'usuarios_historiales_residuos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsuariosRegistroContenedores',
            fields=[
                ('id_usuario_registro_contenedor', models.AutoField(primary_key=True, serialize=False)),
                ('nota_usuario_contenedor', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'usuarios_registro_contenedores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsuariosTienenNotificaciones',
            fields=[
                ('id_usuario_notificacion', models.AutoField(primary_key=True, serialize=False)),
                ('leido', models.BooleanField(blank=True, null=True)),
                ('fecha_recibido', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'usuarios_tienen_notificaciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Zonas',
            fields=[
                ('id_zona', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_zona', models.CharField(blank=True, max_length=50, null=True)),
                ('color_zona', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'zonas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=50)),
                ('apellido_usuario', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('id_direccion', models.ForeignKey(blank=True, db_column='id_direccion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='apiApp.direcciones')),
                ('id_tipo_usuario', models.ForeignKey(blank=True, db_column='id_tipo_usuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='apiApp.tipousuarios')),
                ('id_zona', models.ForeignKey(blank=True, db_column='id_zona', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='apiApp.zonas')),
                ('user', models.OneToOneField(blank=True, db_column='id_user', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'usuarios',
                'managed': True,
            },
        ),
    ]
