# Generated by Django 5.2.5 on 2025-11-24 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0005_calendarios_upgrade'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaNoticias',
            fields=[
                ('id_categoria_noticias', models.AutoField(primary_key=True, serialize=False)),
                ('categoria', models.CharField(max_length=60, unique=True)),
                ('color_hex', models.CharField(max_length=7, unique=True)),
            ],
            options={
                'db_table': 'categoria_noticias',
                'managed': False,
            },
        ),
    ]
