# Generated by Django 5.2.5 on 2025-12-06 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0006_categorianoticias'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coordenadas',
        ),
        migrations.DeleteModel(
            name='SpatialRefSys',
        ),
    ]
