# Generated by Django 5.2.5 on 2025-12-21 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0007_delete_coordenadas_delete_spatialrefsys'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaResiduos',
            fields=[
                ('id_categoria_residuo', models.AutoField(primary_key=True, serialize=False)),
                ('categoria', models.CharField(max_length=60, unique=True)),
                ('color_hex', models.CharField(max_length=7, unique=True)),
            ],
            options={
                'db_table': 'categoria_residuos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExcepcionesRecolecciones',
            fields=[
                ('id_excepciones_recoleccion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.SmallIntegerField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('tipo', models.TextField()),
                ('nueva_fecha', models.DateField()),
                ('nuevo_inicio', models.TimeField()),
                ('nuevo_fin', models.TimeField()),
                ('motivo', models.TextField()),
            ],
            options={
                'db_table': 'excepciones_recolecciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HorariosRecoleccion',
            fields=[
                ('id_horario_recoleccion', models.AutoField(primary_key=True, serialize=False)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('dia_semana', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'horarios_recoleccion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SensorEstadoHistorial',
            fields=[
                ('id_estado', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_estado', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sensor_estado_historial',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SensorEstadosTipos',
            fields=[
                ('id_sensor_estado_tipos', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=60, unique=True)),
                ('descripcion', models.TextField()),
                ('severidad', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'sensor_estados_tipos',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Estados',
        ),
        migrations.DeleteModel(
            name='TipoEstados',
        ),
    ]
