# Generated by Django 5.2.5 on 2026-03-19 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0008_categoriaresiduos_excepcionesrecolecciones_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UmbralLlenado',
            fields=[
                ('id_umbral_llenado', models.AutoField(primary_key=True, serialize=False)),
                ('bajo_max', models.DecimalField(decimal_places=2, max_digits=5)),
                ('medio_max', models.DecimalField(decimal_places=2, max_digits=5)),
                ('alto_max', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'umbral_llenado',
                'managed': False,
            },
        ),
    ]
