# Generated by Django 5.2.5 on 2026-04-01 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0009_umbralllenado'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuariosContenedoresFavoritos',
            fields=[
                ('id_usuario_notificacion', models.AutoField(primary_key=True, serialize=False)),
                ('leido', models.BooleanField(blank=True, null=True)),
                ('fecha_recibido', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'usuario_contenedores_favoritos',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='UsuariosTienenNotificaciones',
        ),
    ]
