# Generated by Django 5.2.5 on 2026-04-01 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0010_usuarioscontenedoresfavoritos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuariosTienenNotificaciones',
            fields=[
                ('id_usuario_notificacion', models.AutoField(primary_key=True, serialize=False)),
                ('leido', models.BooleanField(blank=True, null=True)),
                ('fecha_recibido', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'usuarios_tienen_notificaciones',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='UsuariosRegistroContenedores',
        ),
        migrations.AlterModelTable(
            name='usuarioscontenedoresfavoritos',
            table='usuarios_contenedores_favoritos',
        ),
    ]
